name: Determine build version

on:
    workflow_call:
        outputs:
            version:
                value: ${{ jobs.version.outputs.version }}
            version_tag:
                value: ${{ jobs.version.outputs.version_tag }}
jobs:
    version:
        runs-on: ubuntu-latest
        outputs:
            version: ${{ steps.format_version.outputs.version }}
            version_tag: ${{ steps.semver.outputs.version_tag }}
        steps:
            -   uses: actions/checkout@v4
                with:
                    fetch-depth: 0
            -   name: Determine version
                id: semver
                uses: Paulhatch/semantic-version@v5.0.3
                with:
                    tag_prefix: "v"
                    major_pattern: "major:"
                    minor_pattern: "minor:"
                    version_format: "${major}.${minor}.${patch}"
            -   name: Set version output
                id: format_version
                run: |
                        if [ "${{ github.ref }}" = "refs/heads/main" ]; then
                            echo "version=${{ steps.semver.outputs.version }}" >> $GITHUB_OUTPUT
                        else
                            RC_VERSION="${{ steps.semver.outputs.version }}-rc${{ steps.semver.outputs.increment }}"
                            BRANCH_NAME="${{ github.head_ref || github.ref_name }}"
                            FORMATTED_BRANCH=$(echo $BRANCH_NAME | sed 's/\//-/g')
                            echo "version=${RC_VERSION}-${FORMATTED_BRANCH}" >> $GITHUB_OUTPUT
                        fi